#!/usr/bin/env python3
"""Build the editable README diagrams from bilingual copy and SVG primitives.

Text: diagrams/readme-content.json. Layout, palette, icons: this file.
Run `make readme-diagrams` to build HTML, embed Korean fonts, and export PNGs.
This build step alone uses only the Python standard library and no network.
"""

from pathlib import Path
import json
from html import escape

ROOT = Path(__file__).resolve().parents[1]
PAPER, INK, MUTED, ACCENT, RULE = '#f5f5f5', '#2d3142', '#4f5d75', '#eb6c36', 'rgba(45,49,66,0.12)'

def text(x, y, value, size=16, weight=400, fill=INK, anchor='start', cls=''):
    return f'<text x="{x}" y="{y}" font-size="{size}" font-weight="{weight}" fill="{fill}" text-anchor="{anchor}" class="{cls}">{escape(value)}</text>'

def rect(x, y, w, h, fill=PAPER, stroke='none', rx=8):
    return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" fill="{fill}" stroke="{stroke}"/>'

ICONS = {
    'phone': '<rect x="10" y="2" width="20" height="36" rx="4"/><path d="M16 8h8M18 32h4M16 20l3 3 6-6"/>',
    'search': '<circle cx="17" cy="17" r="12"/><path d="M26 26l10 10M11 17h12M17 11v12"/>',
    'query': '<rect x="2" y="5" width="36" height="30" rx="4"/><path d="M10 15l6 5-6 5M22 25h8"/>',
    'result': '<path d="M12 5H8a4 4 0 0 0-4 4v7l-3 4 3 4v7a4 4 0 0 0 4 4h4M28 5h4a4 4 0 0 1 4 4v7l3 4-3 4v7a4 4 0 0 1-4 4h-4M15 20l4 4 7-8"/>',
    'agent': '<path d="M8 5h24a6 6 0 0 1 6 6v16a6 6 0 0 1-6 6H18l-9 5v-5H8a6 6 0 0 1-6-6V11a6 6 0 0 1 6-6Z"/><circle cx="13" cy="18" r="1"/><circle cx="27" cy="18" r="1"/><path d="M14 25h12"/>',
    'key': '<circle cx="12" cy="13" r="9"/><path d="M18 20l16 16h4v-6l-4-4h-4v-4h-4M9 11h0"/>',
    'web': '<rect x="2" y="5" width="36" height="30" rx="4"/><path d="M2 13h36M8 9h0M14 9h0M15 20l-5 5 5 5M25 20l5 5-5 5"/>',
}

def icon(name, x, y, color=INK, scale=1):
    return f'<g transform="translate({x} {y}) scale({scale})" fill="none" stroke="{color}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{ICONS[name]}</g>'

def arrow(x1, y, x2, slug, color=INK, reverse=False):
    marker = 'white' if reverse else 'ink'
    return f'<path d="M{x1} {y}H{x2}" fill="none" stroke="{color}" stroke-width="2" marker-end="url(#{slug}-arrow-{marker})"/>'

def save(stem, locale, height, title, desc, note, body):
    slug = stem + ('.en' if locale == 'en' else '')
    family = '"Pretendard Variable", "Apple SD Gothic Neo", "Malgun Gothic", sans-serif' if locale == 'ko' else '"Geist", sans-serif'
    html = f'''<!doctype html>
<html lang="{locale}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{escape(title)} — tossctl</title>
<!-- Diagram Design: fit frame, static editorial variation.
     User reference: simple workflow and a strong central system group.
     Approved default palette retained. Korean uses Pretendard as requested.
     English retains Instrument Serif titles and Geist labels. Icon-led steps
     and a dark focus group replace uniform boxes and a redundant legend.
     Generated by tools/build_readme_diagrams.py. Edit the JSON copy or builder. -->
<link href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700&amp;family=Geist+Mono:wght@400;500&amp;family=Instrument+Serif&amp;display=swap" rel="stylesheet">
<style>
* {{ box-sizing: border-box; }}
body {{ margin: 0; padding: 16px; background: {PAPER}; color: {INK}; font-family: {family}; }}
main {{ max-width: 960px; margin: 0 auto; }}
h1 {{ position: absolute; width: 1px; height: 1px; overflow: hidden; clip-path: inset(50%); }}
svg {{ display: block; width: 100%; height: auto; font-family: {family}; }}
:lang(en) .figure-title {{ font-family: "Instrument Serif", serif; font-weight: 400; font-size: 36px; }}
.mono {{ font-family: "Geist Mono", monospace; }}
.note {{ font-size: 16px; line-height: 1.6; color: {MUTED}; margin: 16px 24px; }}
</style>
</head>
<body><main>
<h1>{escape(title)}</h1>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 960 {height}" role="img" aria-labelledby="{slug}-title {slug}-desc">
<title id="{slug}-title">{escape(title)}</title>
<desc id="{slug}-desc">{escape(desc)}</desc>
<defs>
<marker id="{slug}-arrow-ink" viewBox="0 0 8 8" refX="8" refY="4" markerWidth="8" markerHeight="8" markerUnits="userSpaceOnUse" orient="auto"><path d="M0 0L8 4L0 8Z" fill="{INK}"/></marker>
<marker id="{slug}-arrow-white" viewBox="0 0 8 8" refX="8" refY="4" markerWidth="8" markerHeight="8" markerUnits="userSpaceOnUse" orient="auto"><path d="M0 0L8 4L0 8Z" fill="{PAPER}"/></marker>
</defs>
{rect(0, 0, 960, height)}
{body}
</svg>
<p class="note">{escape(note)}</p>
</main></body>
</html>
'''
    target = ROOT / 'diagrams' / (stem + ('.en' if locale == 'en' else '') + '.html')
    target.write_text(html, encoding='utf-8')

def main():
    content = json.loads((ROOT / 'diagrams' / 'readme-content.json').read_text(encoding='utf-8'))
    for locale in ('ko', 'en'):
        copy = content[locale]
        ko = locale == 'ko'
        stem = 'readme-workflow'
        slug = stem + ('' if ko else '.en')
        title = copy['workflow']['title']
        desc = copy['workflow']['description']
        note = copy['workflow']['note']
        body = [text(40, 36, copy['workflow']['eyebrow'], 16, 600, MUTED), text(40, 80, title, 32, 700, cls='figure-title')]
        body += [rect(248, 116, 432, 184, INK), text(272, 144, copy['workflow']['group'], 16, 600, PAPER)]
        # Zone first, connectors next, step icons and labels last.
        body += [arrow(176, 204, 240, slug), arrow(416, 204, 488, slug, PAPER, True), arrow(688, 204, 752, slug)]
        for center, name, label, sub, color in [
            (116, 'phone', copy['workflow']['login'], copy['workflow']['login_hint'], INK),
            (348, 'search', copy['workflow']['select'], copy['workflow']['select_hint'], PAPER),
            (564, 'query', copy['workflow']['query'], copy['workflow']['query_hint'], PAPER),
            (824, 'result', copy['workflow']['result'], copy['workflow']['result_hint'], INK),
        ]:
            body += [icon(name, center - 20, 184, color), text(center, 256, label, 24, 600, color, 'middle'), text(center, 284, sub, 16, 400, color if color == PAPER else MUTED, 'middle')]
        body += [f'<path d="M40 324H920" stroke="{RULE}"/>', f'<circle cx="44" cy="344" r="4" fill="{ACCENT}"/>', text(60, 348, copy['workflow']['footer'], 16, 400, MUTED)]
        save(stem, locale, 376, title, desc, note, '\n'.join(body))

        stem = 'readme-overview'
        slug = stem + ('' if ko else '.en')
        title = copy['overview']['title']
        desc = copy['overview']['description']
        note = copy['overview']['note']
        body = [text(40, 36, copy['overview']['eyebrow'], 16, 600, MUTED), text(40, 80, title, 32, 700, cls='figure-title')]
        body += [rect(320, 128, 272, 248, INK)]
        body += [arrow(240, 188, 312, slug), arrow(240, 312, 312, slug), arrow(600, 188, 680, slug), arrow(600, 312, 680, slug)]
        for y, symbol, label, sub in [
            (144, 'query', copy['overview']['cli_label'], copy['overview']['cli_hint']),
            (268, 'agent', copy['overview']['mcp_label'], copy['overview']['mcp_hint']),
        ]:
            body += [rect(40, y, 200, 88, '#ffffff', RULE), icon(symbol, 56, y + 16, scale=0.8), text(104, y + 36, label, 24, 600), text(56, y + 68, sub, 16, 400, MUTED)]
        body += [text(344, 180, 'tossctl', 32, 500, PAPER, cls='mono'), text(344, 212, copy['overview']['binary'], 16, 400, PAPER)]
        body += [f'<path d="M344 236H568" stroke="rgba(245,245,245,0.24)"/>', text(344, 272, copy['overview']['features_top'], 20, 500, PAPER), text(344, 312, copy['overview']['features_bottom'], 20, 500, PAPER), text(344, 352, 'CLI + MCP', 16, 400, '#bfc0c0', cls='mono')]
        for y, symbol, label, sub in [
            (144, 'key', copy['overview']['official'], copy['overview']['official_hint']),
            (268, 'web', copy['overview']['wts'], copy['overview']['wts_hint']),
        ]:
            body += [rect(688, y, 232, 88, '#ffffff', RULE), icon(symbol, 704, y + 16, scale=0.8), text(748, y + 36, label, 20, 600), text(704, y + 68, sub, 16, 400, MUTED)]
        body += [f'<path d="M40 400H920" stroke="{RULE}"/>', text(40, 428, copy['overview']['footer'], 16, 400, MUTED)]
        save(stem, locale, 456, title, desc, note, '\n'.join(body))

    print('Built four standalone HTML diagrams from readme-content.json.')


if __name__ == '__main__':
    main()
